export {default as Home} from "./Home.vue"
export {default as About} from "./About.vue"
export {default as Contac} from "./Contact.vue"
export {default as Project} from "./Project.vue"
export {default as Services} from "./Services.vue"